---
title: "Top Chef"
author: "Sruthi Srikantan"
date: "2023-12-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library("topChef")
```
1.
```{r}
library(dplyr)
filtered_chefdetails <- chefdetails %>%
  filter(!grepl("Masters|Canada", season, ignore.case = TRUE))

filtered_judges <- judges %>%
  filter(!grepl("Masters|Canada", season, ignore.case = TRUE))

```

2.
```{r}
filtered_chefdetails <- filtered_chefdetails %>%
  select(season, seasonNumber, name, placement,gender)


filtered_judges <- filtered_judges %>%
  select(season,seasonNumber, episode, challengeType,guestJudge,competedOnTC)

```
3.
```{r}
unique_seasons <- unique(filtered_chefdetails$season)

# Create a data frame with season numbers
season_mapping_chef <- data.frame(
  season = unique_seasons,
  seasonNumber = unique(filtered_chefdetails$seasonNumber)
)


```
4a.170 male contestants and 152 female contestants
```{r}
head(filtered_chefdetails)
sum(filtered_chefdetails$gender=="Male")
sum(filtered_chefdetails$gender=="Female")
```
4b.14 male and 6 female
```{r}
winners_placement_1 <- subset(filtered_chefdetails, placement == 1)
sum(winners_placement_1$gender=="Male")
sum(winners_placement_1$gender=="Female")

```
4c.15 male 7 female 
```{r}
winners_placement_123 <- subset(filtered_chefdetails, placement==c(1,2,3))
winners_placement_123
sum(winners_placement_123$gender=="Male")
sum(winners_placement_123$gender=="Female")
```
4d. There are 7 females placed in the top 3 and 6 females that made it to winning spot. This makes sense as the top 3 doesn't indicate that everyone in it will win with a placement equal to 1. 
```{r}
data.frame(sum(winners_placement_1$gender=="Female"),
sum(winners_placement_123$gender=="Female"))
```
4.
```{r}
winners_placement_1 <- subset(filtered_chefdetails, placement == 1)
df1<-filtered_chefdetails
df2<-filtered_judges
merged_df <- merge(df1, df2, by = "seasonNumber", all = TRUE)
merged_df

first_place_winners <- merged_df %>%
  filter(placement == 1) %>%  # Selecting only first-place winners
  mutate(guestJudge_1 = ifelse(name %in% guestJudge, "Yes", "No"))

first_place_winners<- first_place_winners %>%
  select(name,seasonNumber,guestJudge_1)


```
5.
```{r}
not_first_place_guest_judges <- merged_df %>%
  filter(placement!=1) %>%  # Filtering out first-place winners
  filter(name %in% guestJudge) %>%  # Filtering those who served as guest judges
  distinct(name)

```

